testDropDbOnRedhatSuccess:
  testSuites: [postgresql, postgresql-maintenance]
  testFlowPath: io.cloudslang.postgresql.maintenance.test_drop_db_on_redhat
  inputs:
    - hostname: 'ec2-107-21-171-41.compute-1.amazonaws.com'
    - username: 'ec2-user'
    - db_name: 'cs_test'
    - private_key_file: './rhel-psql-aws.pem'
  description: "Tests that run drop_db_on_redhat.sl to drop a database and finishes with SUCCESS"
  result: SUCCESS

testDropDbWithInvalidUsernameOnRedhatFailure:
  testSuites: [postgresql, postgresql-maintenance]
  testFlowPath: io.cloudslang.postgresql.maintenance.test_create_db_on_redhat
  inputs:
    - hostname: 'ec2-107-21-171-41.compute-1.amazonaws.com'
    - username: 'invalid-username'
    - private_key_file: './rhel-psql-aws.pem'
  description: "Test that run drop_db_on_redhat.sl with invalid username and finishes with Auth failure"
  outputs:
    -  return_result: 'com.jcraft.jsch.JSchException: Auth fail'
  result: FAILURE

testDropDbWithInvalidInstallationLocationOnRedhatFailure:
  testSuites: [postgresql,postgresql-maintenance]
  testFlowPath: io.cloudslang.postgresql.maintenance.test_create_db_on_redhat
  inputs:
    - hostname: 'ec2-107-21-171-41.compute-1.amazonaws.com'
    - username: 'ec2-user'
    - installation_location: '/some/path'
    - private_key_file: './rhel-psql-aws.pem'
  description: "Tests that run drop_db_on_redhat.sl to drop a database with invalid installation_location and finishes with FAILURE"
  outputs:
    - exception: 'pg_ctl: directory "/some/path" does not exist'
  result: FAILURE

testDropDbWithInvalidPgCtlLocationOnRedhatFailure:
  testSuites: [postgresql,postgresql-maintenance]
  testFlowPath: io.cloudslang.postgresql.maintenance.test_create_db_on_redhat
  inputs:
    - hostname: 'ec2-107-21-171-41.compute-1.amazonaws.com'
    - username: 'ec2-user'
    - pg_ctl_location: '/some/path'
    - private_key_file: './rhel-psql-aws.pem'
  description: "Tests that run drop_db_on_redhat.sl to drop a database with invalid pg_ctl_location and finishes with FAILURE"
  outputs:
    - exception: '-bash: /some/path/pg_ctl: No such file or directory'
  result: FAILURE
